### ISSUE TITLE
app.js don't start

### ISSUE THREAD

**Issue by vitorgamer58** [Karbovanets/karbo-nodes-map#2]
/home/vitorgamer58/map/app.js:11
app.get('/', async (req, res) => {
                               ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

Google Cloud - Ubuntu 14.04
Node Version v0.10.25

**Comment by vitorgamer58** [comment]
resolved using node 8.9.4
